# Generated by Django 4.0.6 on 2022-08-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentogato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alimentopeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alimentoperro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
