# Generated by Django 4.0.6 on 2022-08-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appveterinaria', '0003_alimentopeces_alimentoperro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentogato',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentopeces',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentoperro',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
