# Generated by Django 4.0.6 on 2022-08-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appveterinaria', '0004_alter_alimentogato_precio_alter_alimentopeces_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentogato',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='alimentopeces',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='alimentoperro',
            name='stock',
        ),
    ]
