# Generated by Django 4.0.6 on 2022-08-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appveterinaria', '0005_remove_alimentogato_stock_remove_alimentopeces_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentogato',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='alimentopeces',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='alimentoperro',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='alimentogato',
            name='info',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='alimentopeces',
            name='info',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='alimentoperro',
            name='info',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
